server:
  http_listen_port: 9009

distributor:
  sharding_enabled: true

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory

querier:
  query_ingesters_within: 1h
  query_timeout: 2m

store_gateway:
  sharding_enabled: true

limits:
  enforce_metric_name: true
  reject_old_samples: true
  reject_old_samples_max_age: 168h

schema:
  configs:
    - from: "2023-01-01"
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h
      chunks:
        prefix: chunks_
        period: 168h

storage:
  backend: filesystem
  filesystem:
    dir: /path/to/storage
