#------------------------------------------
# GitHub Actions automation QA-Basics
# ENGINE_MODE_v1.0
# Devopsity (R)                  2022
#------------------------------------------

name: awst-engine

on:
 repository_dispatch:
    
jobs:
  automation-test:
    name: Run_Godog_auto_tests
    if: github.event.action == 'on-demand-test'
    runs-on: ubuntu-latest

    steps:
      - name: Use actions/checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.x'
         
      - name: Setup Godog
        run:
          go install github.com/cucumber/godog/cmd/godog@latest
          
      - name: Copy Envas
        run: 
          cp .env.dist .env
           
      - name: Connect to private repo
        run: 
          git config --global url.https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/.insteadOf https://github.com/

      - name: Set env & Run godog test
        timeout-minutes: 25
        env: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          AUTH0_BASE_EMAIL: ${{ secrets.AUTH0_BASE_EMAIL }}
          AUTH0_BASE_EMAIL_EXISTING: ${{ secrets.AUTH0_BASE_EMAIL_EXISTING }}
          AUTH0_CLIENT: ${{ secrets.AUTH0_CLIENT }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_PASSWORD: ${{ secrets.AUTH0_PASSWORD }}
          AUTH0_PASSWORD_EXISTING: ${{ secrets.AUTH0_PASSWORD_EXISTING }}
          ECDSA_SIGNING_KEY: ${{ secrets.ECDSA_SIGNING_KEY }}
          ENGINE_CLIENT: "engine"
          GODOG_MODE: "ENGINE_MODE"
          GOPRIVATE: "github.com/awst-global"
          STRIPE_2FA_GSM: ${{ secrets.STRIPE_2FA_GSM }}
          UTILITY_KEY: ${{ secrets.UTILITY_KEY }}
        run:
          godog run features/${{ env.ENGINE_CLIENT }}
